import React from 'react';
import { Link } from 'react-router-dom';
import Header from '../components/layout/Header';   
import Footer from '../components/layout/Footer';

const DisclaimerPage = () => {
     const companyName = "18Novem Techologies";

    return (
        <div>
<Header>    </Header>
<div  className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-3xl mx-auto bg-white p-8 shadow rounded-lg">
                <h1 className="text-3xl font-bold text-gray-800 mb-6">Disclaimer</h1>

                <div className="prose prose-indigo max-w-none text-gray-700 space-y-4">
                     <p>Last Updated: April 24, 2025</p>

                    <p>The information contained on the ClientWise website and within the ClientWise software (the "Service") is for general information purposes only.</p>

                    <p>{companyName} assumes no responsibility for errors or omissions in the contents on the Service.</p>

                    <p>In no event shall {companyName} be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. {companyName} reserves the right to make additions, deletions, or modification to the contents on the Service at any time without prior notice.</p>

                    <p>{companyName} does not warrant that the website is free of viruses or other harmful components.</p>

                    <h2>Financial Disclaimer</h2>
                    <p>The Service provides tools for insurance agents and advisors but does not provide financial, investment, or insurance advice. Any information, calculations, estimations (including AI-generated suggestions or coverage estimations), or recommendations provided by the Service are for informational and organizational purposes only. You are solely responsible for the advice you provide to your clients and for verifying the accuracy and suitability of any information generated by the Service before presenting it to clients or making decisions based upon it. Always consult with qualified professionals and verify details directly with insurance providers.</p>

                    <h2>External Links Disclaimer</h2>
                    <p>The ClientWise website may contain links to external websites that are not provided or maintained by or in any way affiliated with {companyName}. Please note that {companyName} does not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.</p>

                     <h2>Affiliate Disclaimer</h2>
                     <p>[Placeholder: Include if you use affiliate links.]</p>

                </div>

                <div className="mt-8 text-center">
                    <Link to="/" className="text-indigo-600 hover:text-indigo-800 text-sm">
                        &larr; Back to Home
                    </Link>
                </div>
            </div></div>
            <Footer></Footer>
        </div>
    );
};

export default DisclaimerPage;
